### ISSUE TITLE
Cannot show correctly with CJK characters in Win10

### ISSUE THREAD

**Issue by Ka-lip** [vifm/vifm#702]
Hello,

I encountered an issue that vifm cannot display correctly with CJK characters if I change the terminal size or move around the files with CJK filenames.

This is correct situation.
![image](https://user-images.githubusercontent.com/22840544/129705162-0a7a99a0-75b5-4d25-a3e3-c00ca6d9eae8.png)

But after it becomes weird (e.g. the selection bar goes through these files, or I resize the terminal), I cannot solve it by all means, and I can only turn the window(terminal tab) off and restart.
![image](https://user-images.githubusercontent.com/22840544/129704919-388e1bd8-5153-42bd-933f-a69524510743.png)

I have surveyed the issues pages and google it, 
A very similar issue in [Vifm Q&A](http://q2a.vifm.info/601/chinese-file-and-folder-names-are-not-correctly-displayed), and the author said it was solved, but I still encounter this issue.

Is there anyone knowing the solution? Or it is a bug?

**Comment by xaizek** [comment]
Hello,

> I cannot solve it by all means, and I can only turn the window(terminal tab) off and restart.

I'd expect <kbd>Ctrl+L</kbd> to fix it temporarily.

> A very similar issue in Vifm Q&A, and the author said it was solved, but I still encounter this issue.

I think it was solved in Microsoft Terminal, maybe not anywhere else.

> Is there anyone knowing the solution? Or it is a bug?

It looks as if libpdcurses failed to recognize CJK characters. You can see it on the first screenshot as well (lighter characters on the far right). I had to patch the library to make it work with CJK, but it seems to not work sometimes and might depend on the terminal. I can take a look at it again (maybe newer `cmder` works differently), but I pretty much tried all I could do about it before.

**Comment by xaizek** [comment]
Actually, I might know what's the issue here.

Try undefining `ConEmuANSI` environment variable or just set it to anything other than `ON` before starting Vifm. Looks like I might need to add more changes to teach ANSI output mode of pdcurses to deal with CJK (it's used for 256 colors).

**Comment by Ka-lip** [comment]
Hello Mr. zaizek, 

Thank you for the reply. I also saw you were trying to solve that problem before. 😄 

> I think it was solved in Microsoft Terminal, maybe not anywhere else.

Actually I am using `Windows terminal`, and vifm behaves strange on both `Windows terminal` & `cmder`.
The result are a little bit different but both are strange so I think the root cause is the same. 
(I am sure that I use the latest version Windows terminal & vifm)

The origin powershell could not show CJK characters, then the display is normal.
![image](https://user-images.githubusercontent.com/22840544/129837091-f9d11782-3073-428e-ae5b-bdd089fe9fb5.png)

When it is cmder, it is not as strange as `Windows terminal` but it is still no able to be used.
![image](https://user-images.githubusercontent.com/22840544/129837633-6741075b-7984-42cc-85e3-ec38f25ee129.png)

(<kbd>Ctrl</kbd> + <kbd>L</kbd> does not work on both terminal.)

Sorry for that I could not code to solve this bug, but if anything information you need, please feel free to ask!

**Comment by xaizek** [comment]
Windows terminal seems to not use a suitable font.

Have you tried setting the variable for `cmder`?
```
export ConEmuANSI=OFF
```
in `bash` or in `cmd.exe`:
```
set ConEmuANSI=OFF
```
Not sure what's the syntax in `powershell`.

**Comment by Ka-lip** [comment]
Thanks for replying!

I tried 
```
set ConEmuANSI=OFF
```

but it is still the same in cmder. I also changed to another PC (Windows 7 with Japanese environment), but the rendering of cmder (git-bash & cmd) is still strange (though the strange appearance is a little bit different).

I think one possible underlying problem might be the length of CJK characters are longer than it should be. 
You can check the last one picture I posted. It looks like some spaces are in each characters in `質問事項.docx` `05第五講　閩南語音韻系統.pdf`

And the font of terminal should not be the problem because CJK characters look good in neovim & vim.

I don't expect this bug can be fixed right now, but I hope what I reported can be helpful for your development in the future.
I know encoding are troublesome... Thank you for your enthusiasm! 😭

**Comment by xaizek** [comment]
Font-picking dialogs on Windows also list character sets. This might have something to do with it. Maybe some of these will be helpful:
* https://www.curlybrace.com/words/2014/10/03/windows-console-and-doublemulti-byte-character-set/
* https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8
* https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line
I'm not sure, maybe Vifm should set character set for CJK to always work (`chcp` does it, so must be possible).
